class AuthErrors {
  static const ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD";
  static const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
  static const ERROR_USER_DISABLED = "ERROR_USER_DISABLED";
  static const ERROR_WEAK_PASSWORD = "ERROR_WEAK_PASSWORD";
  static const ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL";
  static const ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_IN_USE";
  static const ERROR_INVALID_CREDENTIAL = "ERROR_INVALID_CREDENTIAL";
  static const ERROR_REQUIRES_RECENT_LOGIN = "ERROR_REQUIRES_RECENT_LOGIN";
  static const ERROR_OPERATION_NOT_ALLOWED = "ERROR_OPERATION_NOT_ALLOWED";  
  static const ERROR_MISSING_EMAIL = "ERROR_MISSING_EMAIL";
}
